### ISSUE TITLE
Crash if I add item to list and then change the amount in cupboard

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Cupboard#99] opened 2018-04-17 23:59 UTC
![screencast 2018-04-17 19-57-37](https://user-images.githubusercontent.com/228704/38904670-b3ab148c-4279-11e8-88f5-8075fcbcdf59.gif)

**Comment by WillWells** [comment] 2018-04-20 01:43
![85734ef7de6605d2e4417ea8fa036d33](https://user-images.githubusercontent.com/14840166/39026330-786c1ef0-441a-11e8-828f-beb29748fdbb.gif)

I could not recreate the issue. Can anyone else confirm they are having this issue? Using emulator with Android 8.0 API 26

**Comment by parsonsbatsc** [comment] 2018-04-20 18:43
Confirmed on Galaxy S7.  I also had it crash when trying to change the quantity while entering it in the first place.

**Comment by WillWells** [comment] 2018-04-20 19:07
@josemvidal @parsonsbatsc could one or both of you confirm that this crash happens with accounts created AFTER the release date of RC1? It's possible that old data from Firebase could cause a crash when it does not have values the RC1 release of the app is searching for.

Alternatively, deleting all of your foods and shopping lists in your current accounts should have the same effect.

And @parsonsbatsc, regarding the second crash, do you mean when the food is first created, or do you mean you get the same crash described in this issue without having to add the food to the list first? I'd be surprised if there was a crash in Manual Entry, but with the latter case, we did have a bug that caused crashes that I believed I had fixed here b38a28e.

**Comment by parsonsbatsc** [comment] 2018-04-20 19:17
The crash was when the food was first created, and this was with an account that I just created.

**Comment by WillWells** [comment] 2018-04-20 23:26
![f3888f6e659abeffcba1031e8d56d2b8](https://user-images.githubusercontent.com/14840166/39077509-6bc4d370-44d0-11e8-8ffb-f7917f09563c.png)
Adding this for stack trace reference since it took so long to recreate this bug, in case I cannot recreate it again. It is same issue I thought I fixed with b38a28e.

**Comment by WillWells** [comment] 2018-04-20 23:56
Hopefully fixed with 4859431 but requires further testing to be sure.

**Comment by WillWells** [comment] 2018-05-01 01:00
Could not reproduce since last mentioned commit.

**Closed by WillWells** 2018-05-01 01:00 UTC
Labels: bug
